# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/100-Working/105-Working-improvement/github_lib/k7_neorv32/constrs/debug.xdc

# XDC: C:/100-Working/105-Working-improvement/github_lib/k7_neorv32/constrs/flash.xdc

# XDC: C:/100-Working/105-Working-improvement/github_lib/k7_neorv32/constrs/pin.xdc

# XDC: C:/100-Working/105-Working-improvement/github_lib/k7_neorv32/constrs/timing.xdc

# IP: C:/100-Working/105-Working-improvement/github_lib/k7_neorv32/ip/uihdmitx_1/uihdmitx_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uihdmitx_1 || ORIG_REF_NAME==uihdmitx_1} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_0/design_1_s00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_0 || ORIG_REF_NAME==design_1_s00_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_data_fifo_0/design_1_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_0 || ORIG_REF_NAME==design_1_s00_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s01_regslice_0 || ORIG_REF_NAME==design_1_s01_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s01_data_fifo_0/design_1_s01_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s01_data_fifo_0 || ORIG_REF_NAME==design_1_s01_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s02_regslice_0/design_1_s02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s02_regslice_0 || ORIG_REF_NAME==design_1_s02_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s02_data_fifo_0/design_1_s02_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s02_data_fifo_0 || ORIG_REF_NAME==design_1_s02_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s03_regslice_0/design_1_s03_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s03_regslice_0 || ORIG_REF_NAME==design_1_s03_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s03_data_fifo_0/design_1_s03_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s03_data_fifo_0 || ORIG_REF_NAME==design_1_s03_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_data_fifo_0/design_1_m00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m00_data_fifo_0 || ORIG_REF_NAME==design_1_m00_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_0 || ORIG_REF_NAME==design_1_m00_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0/design_1_axi_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0 || ORIG_REF_NAME==design_1_axi_interconnect_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_0 || ORIG_REF_NAME==design_1_mig_7series_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_mig_7series_0_100M_0/design_1_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==design_1_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# XDC: c:/100-Working/105-Working-improvement/github_lib/k7_neorv32/k7_dma/k7_dma.gen/sources_1/bd/design_1/design_1_ooc.xdc
