# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/100-Working/105-Working-improvement/github_lib/k7_neorv32/k7_dma/k7_dma.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0.xci
# IP: The module: 'design_1_m00_regslice_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/100-Working/105-Working-improvement/github_lib/k7_neorv32/k7_dma/k7_dma.gen/sources_1/bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_m00_regslice_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/100-Working/105-Working-improvement/github_lib/k7_neorv32/k7_dma/k7_dma.gen/sources_1/bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_m00_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/100-Working/105-Working-improvement/github_lib/k7_neorv32/k7_dma/k7_dma.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0.xci
# IP: The module: 'design_1_m00_regslice_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/100-Working/105-Working-improvement/github_lib/k7_neorv32/k7_dma/k7_dma.gen/sources_1/bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_m00_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/100-Working/105-Working-improvement/github_lib/k7_neorv32/k7_dma/k7_dma.gen/sources_1/bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_m00_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
